steps:
- name: 'gcr.io/cloud-builders/docker'
  args: ['build', '-t', 'gcr.io/${_PROJECT_ID}/firebase', '.']
images:
- 'gcr.io/${_PROJECT_ID}/firebase'
tags: ['cloud-builders-community']

substitutions:
  _PROJECT_ID: landsandhomes2024
